[tool.poetry]
name = "dmidecode"
version = "0.1.0"
description = "dmidecode parser"
authors = ["Kevin Thomas <hamgom95@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
